build-development:
  environment:
    name: development
  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'
      when: always
  image: docker:latest
  stage: build
  script:
    - cp $ENV .env.local
    - docker build -t $CI_REGISTRY_IMAGE:dev .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:dev

deploy-development:
  environment:
    name: development
  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'
      when: always
  image: alpine:latest
  stage: deploy
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/gitlab
    - chmod 700 ~/.ssh/gitlab
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/gitlab
    - ssh-keyscan -H "$REMOTE_HOST" >> ~/.ssh/known_hosts
  script:
    - cat $DEPLOY_SCRIPT > deploy.sh
    - chmod +x ./deploy.sh
    - sh ./deploy.sh
