export const getMappedType = (foundType: { label: string; value: number }) => {
  const mappedType1 = [
    "Chăn, Ga, Gối & Nệm",
    "Đồ nội thất",
    "Trang trí nhà cửa",
    "Đồ dùng nhà bếp",
    "Đèn",
    "Giặt là",
    "Đồ dùng phòng tắm",
    "Đồ dùng phòng ăn",
    "Tinh dầu thơm",
    "Ngoài trời & Sân vườn",
    "Áo khoác",
    "Áo Vest và Blazer",
    "Áo hoodie, Len, Nỉ",
    "Áo sơ mi cộc tay",
    "Áo sơ mi dài tay",
    "Áo ba lỗ",
    "Quần jeans",
    "Quần dài/ Quần âu",
    "Quần short",
    "Đồ ngủ",
    "Đồ lót",
    "Tất / vớ",
    "Thắt lưng",
    "Cà vạt",
    "Phụ kiện",
    "Quần ",
    "Quần đùi",
    "Chân váy",
    "Quần jeans",
    "Đầm/Váy",
    "Váy cưới",
    "Đồ liền thân",
    "Áo khoác",
    "Áo len & Cardigan",
    "Hoodie và Áo nỉ",
    "Đồ bộ",
    "Đồ lót",
    "Đồ ngủ",
    "Đồ bầu",
    "Đồ hoá trang",
    "Áo",
    "Vớ/Tất",
    "Thịt",
    "Cá",
    "Hải sản",
    "Rau ",
    "Hoa quả tươi",
    "Hoa quả sấy khô",
    "Đồ khô",
    "Đồ ăn vặt",
    "Đồ uống có cồn",
    "Nguyên liệu nấu ăn",
    "Đồ làm bánh",
    "Sữa - trứng",
    "Đồ uống",
    "Ngũ cốc",
    "Các loại bánh",
    "Sách tiếng Việt",
    "Sách nước ngoài",
    "Bút viết",
    "Dụng cụ học sinh và văn phòng phẩm",
    "Đồ vẽ",
    "Sổ, giấy các loại",
    "Balo nữ",
    "Balo nam",
    "Cặp laptop",
    "Ví nữ",
    "Ví nam",
    "Túi tote",
    "Túi đeo chéo nữ",
    "Túi đeo chéo nam",
    "Túi đeo hông",
    "Phụ kiện túi",
    "Thức ăn cho thú cưng",
    "Phụ kiện",
    "Vệ sinh",
    "Quần áo",
    "Chăm sóc sức khoẻ",
    "Làm đẹp",
    "Khác",
    "Đồ chơi mô hình",
    "Đồ chơi giải trí",
    "Đồ chơi giáo dục",
    "Đồ chơi cho trẻ sơ sinh",
    "Đồ chơi vận động ngoài trời",
    "Búp bê và đồ chơi nhồi bông",
    "Thiết bị đeo thông minh",
    "Phụ kiện tivi",
    "Máy game",
    "Linh kiện",
    "Tai nghe",
    "Tivi",
    "Loa",
    "Máy tính bàn",
    "Màn hình",
    "Linh kiện máy tính",
    "Thiết bị lưu trữ",
    "Thiết bị mạng",
    "Máy in, scan, Máy chiếu",
    "Laptop",
    "Phụ kiện máy tính",
    "Khác",
    "Bốt",
    "Giày thể thao",
    "Giày đế bằng",
    "Giày cao gót",
    "Giày đế xuồng",
    "Xăng đan và dép",
    "Phụ kiện giày",
    "Khác",
    "Bốt",
    "Giày thể thao",
    "Giày sục",
    "Giày tây lười",
    "Giày oxfords và giày buộc dây",
    "Xăng đan và dép",
    "Phụ kiện giày dép",
    "Khác",
    "Thiết bị HomeIOT",
    "Nhà thuốc - hiệu thuốc",
    "Mỹ phẩm",
    "Gỗ",
    "Gốm",
    "Lụa",
    "Mây tre đan",
    "Sơn mài",
    "Nón",
    "Đúc đồng",
    "Dân gian",
  ].map((v) => v.toLocaleLowerCase());
  const mappedType2 = [
    "Spa",
    "Nail",
    "Thẩm mỹ",
    "Hair salon",
    "Nhà hàng ",
    "Quán cafe",
    "Trung tâm tổ chức sự kiện",
    "Ẩm thực đường phố",
    "Nhà nghỉ",
    "Khách sạn",
    "Resort",
    "Homestay",
    "Nhà trọ",
    "Bóng đá",
    "Cầu lông",
    "Bóng rổ",
    "Tennis",
    "Bóng chuyền",
    "Bi-a",
    "Gym",
    "Golf",
    "Rạp chiếu phim",
    "Rạp hát-nhà hát",
    "Phòng trà",
    "Karaoke",
    "Nhà múa rối",
    "Rạp xiếc",
    "Quán bar",
    "Quán game - quán net",
    "Trung tâm vui chơi",
    "Công viên",
  ].map((v) => v.toLocaleLowerCase());
  const mappedType3 = [
    "Bệnh viện",
    "Y tế tại gia",
    "Trạm y tế",
    "Phòng khám thú y",
    "Nha khoa",
    "Phòng khám tư nhân",
    "Mầm non",
    "Tiểu học",
    "Trung học cơ sở",
    "Trung tâm Giáo dục thường xuyên",
    "Trung học phổ thông",
    "Trung cấp",
    "Cao đẳng",
    "Đại học",
    "Trung tâm dạy nhạc",
    "Trung tâm tiếng Anh",
    "Trung tâm luyện thi THPT",
    "Trung tâm dạy nghề",
    "Gia sư",
    "TT đào tạo lái xe",
    "Thuê xe đạp",
    "Thuê xe máy",
    "Thuê oto dịch vụ",
    "Cửa hàng bán xe đạp",
    "Cửa hàng bán xe máy",
    "Showroom Otô",
    "Điểm đỗ xe bus",
    "Bãi đỗ xe",
    "Điểm du lịch",
    "Di tích lịch sử",
    "Camping",
    "Vườn Quốc gia",
    "Điện tử, điện lạnh",
    "Điện nước ",
    "Nội thất ",
    "Giặt là ",
    "Rửa xe",
    "Ô tô",
    "Xe máy, xe đạp ",
    "Điện thoại ",
    "Máy tính",
    "Cứu hộ",
    "Giúp việc",
    "Môi giới việc làm",
  ].map((v) => v.toLocaleLowerCase());
  if (mappedType1.includes(foundType.label.toLocaleLowerCase())) return 1;
  if (mappedType2.includes(foundType.label.toLocaleLowerCase())) return 2;
  if (mappedType3.includes(foundType.label.toLocaleLowerCase())) return 3;
  return 0;
};
